### ISSUE TITLE
New italics variant?

### ISSUE THREAD

**Issue by rcrooks** [N-l1/blue-cheese#4]
HI @N-l1 - I really like this theme and the way it's evolving.
...so, yesterday I started playing around with it - I like a few more italics for code visual parsing, and so added a few in a variant version - not a lot, mainly HTML attribute names and JS function/method names.

If you're open to adding this, I'll create a pull request. Fully understand if you'd rather not.
Best,
Robert
![2021-02-14_09-37-14](https://user-images.githubusercontent.com/619617/107879742-a8c55d80-6ea8-11eb-8c92-bd5ab0b2a94d.png)

**Comment by qiz-li** [comment]
Of course! PRs are always welcomed. I might have a few tweaks but you are definitely welcomed to! 

A side note, would you kindly point me to the font you are using? It looks very nice.

**Comment by rcrooks** [comment]
Great - I'll create the PR. 

The font is monofur - long my favorite: https://www.fontspace.com/monofur-font-f39937

**Comment by qiz-li** [comment]
Added as part of #5
